GET http://45.189.154.9:2000/api/v1/Empresa/Listar
Accept: application/json

###
POST http://45.189.154.9:2000/api/v1/Empresa/Crear
Content-Type: application/json
Accept: application/json

{
    "nombreEmpresa": "Test Empresa",
    "cveEmpresa": "1"
}

