// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api_businesspro.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20240506005716_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("API.Models.AccionesCampoDetalleRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccionCampoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEClasificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<string>("CveOperacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdParte")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Tiempo")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AccionCampoID");

                    b.ToTable("AccionesCampoDetalleRequest");
                });

            modelBuilder.Entity("API.Models.AccionesCampoSeriesRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccionCampoID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BRealizado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEDistribuidor")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaRealizacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioActualiza")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccionCampoID");

                    b.ToTable("AccionesCampoSeriesRequest");
                });

            modelBuilder.Entity("API.Models.CrearAccionesCampoRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CETipoCampana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CitaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CveAccionesCampo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaInicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaTermino")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KilometrajeLimite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreAccionesCampo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreResponsable")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CitaID");

                    b.ToTable("CrearAccionesCampoRequest");
                });

            modelBuilder.Entity("API.Models.CrearCitaRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnModelo")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("BConfirmacion")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("BServicioCitaRepro")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("BServicioExpress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEAsesor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CEColorExterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("CEColorInterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("CEEstatusCita")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CEMarca")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Conductor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Contacto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CveCitaExterna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CveUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FechaCita")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaCitaReal")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaDOFU")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraCita")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraCitaReal")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdDocInterf")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdOrden")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdServicioCitaRepro")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdUnidadesCatalogo")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterfazOrigen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kilometraje")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedioTransporte")
                        .HasColumnType("TEXT");

                    b.Property<string>("MortivoServicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObsExternas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Per_idpersona")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placas")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Propietario")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponsableMtto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CrearCitaRequest");
                });

            modelBuilder.Entity("API.Models.CrearPaqueteOperacionesResquest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoEreact")
                        .HasColumnType("TEXT");

                    b.Property<int>("Costo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CveOperacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("CvePaqueteServ")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPaqueteServConse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelMO")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PaqueteID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioVenta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepTiempo")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoMO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnidadesTimpo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaqueteID");

                    b.ToTable("CrearPaqueteOperacionesResquest");
                });

            modelBuilder.Entity("API.Models.CrearPaquetePartesResquet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadPartes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CtoUniEst")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CvePaqueteServ")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdParte")
                        .HasColumnType("TEXT");

                    b.Property<long>("PaqueteID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioUnitario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoPrecio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaqueteID");

                    b.ToTable("CrearPaquetePartesResquet");
                });

            modelBuilder.Entity("API.Models.CrearPaqueteRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BExclusivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CitaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CvePaqueteServ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionPaqueteServ")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaCTprecio")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaCTref")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdTaller")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MoCosto")
                        .HasColumnType("REAL");

                    b.Property<double>("MoVenta")
                        .HasColumnType("REAL");

                    b.Property<string>("NombrePaqueteServ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origen")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PorIva")
                        .HasColumnType("REAL");

                    b.Property<double>("PrecioUT")
                        .HasColumnType("REAL");

                    b.Property<double>("ReCosto")
                        .HasColumnType("REAL");

                    b.Property<double>("ReVenta")
                        .HasColumnType("REAL");

                    b.Property<double>("TtCosto")
                        .HasColumnType("REAL");

                    b.Property<double>("TtVenta")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CitaID");

                    b.ToTable("CrearPaqueteRequest");
                });

            modelBuilder.Entity("API.Models.CrearPaqueteTotsResquest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoEreact")
                        .HasColumnType("TEXT");

                    b.Property<int>("Costo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CvePaqueteServ")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPaqueteServConse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<long>("PaqueteID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoTT")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaqueteID");

                    b.ToTable("CrearPaqueteTotsResquest");
                });

            modelBuilder.Entity("API.Models.CrearPaqueteVehiculoResquest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CvePaqueteServ")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCatalogo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasColumnType("TEXT");

                    b.Property<long>("PaqueteID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaqueteID");

                    b.ToTable("CrearPaqueteVehiculoResquest");
                });

            modelBuilder.Entity("API.Models.AccionesCampoDetalleRequest", b =>
                {
                    b.HasOne("API.Models.CrearAccionesCampoRequest", "AccionCampo")
                        .WithMany("Detalles")
                        .HasForeignKey("AccionCampoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionCampo");
                });

            modelBuilder.Entity("API.Models.AccionesCampoSeriesRequest", b =>
                {
                    b.HasOne("API.Models.CrearAccionesCampoRequest", "AccionCampo")
                        .WithMany("Series")
                        .HasForeignKey("AccionCampoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionCampo");
                });

            modelBuilder.Entity("API.Models.CrearAccionesCampoRequest", b =>
                {
                    b.HasOne("API.Models.CrearCitaRequest", "Cita")
                        .WithMany("AccionesCampo")
                        .HasForeignKey("CitaID");

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("API.Models.CrearPaqueteOperacionesResquest", b =>
                {
                    b.HasOne("API.Models.CrearPaqueteRequest", "Paquete")
                        .WithMany("Operaciones")
                        .HasForeignKey("PaqueteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("API.Models.CrearPaquetePartesResquet", b =>
                {
                    b.HasOne("API.Models.CrearPaqueteRequest", "Paquete")
                        .WithMany("Partes")
                        .HasForeignKey("PaqueteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("API.Models.CrearPaqueteRequest", b =>
                {
                    b.HasOne("API.Models.CrearCitaRequest", "Cita")
                        .WithMany("Paquetes")
                        .HasForeignKey("CitaID");

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("API.Models.CrearPaqueteTotsResquest", b =>
                {
                    b.HasOne("API.Models.CrearPaqueteRequest", "Paquete")
                        .WithMany("Tots")
                        .HasForeignKey("PaqueteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("API.Models.CrearPaqueteVehiculoResquest", b =>
                {
                    b.HasOne("API.Models.CrearPaqueteRequest", "Paquete")
                        .WithMany("Vehiculos")
                        .HasForeignKey("PaqueteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("API.Models.CrearAccionesCampoRequest", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("API.Models.CrearCitaRequest", b =>
                {
                    b.Navigation("AccionesCampo");

                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("API.Models.CrearPaqueteRequest", b =>
                {
                    b.Navigation("Operaciones");

                    b.Navigation("Partes");

                    b.Navigation("Tots");

                    b.Navigation("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
